#!/usr/bin/env bash

sudo apt-get -y upgrade

# install pip package manager
sudo apt-get install -y python3-pip

# install packages for vit env setup
sudo apt-get install build-essential libssl-dev libffi-dev python3-dev

sudo apt-get install -y python3-venv

mkdir environments
cd environments

pyvenv jupyter-notebook

source jupyter-notebook/bin/activate


python3 -m pip install jupyter

jupyter notebook
