#!/usr/bin/env bash

DOMAIN=${1?ERROR: No domain name given}

#sudo apt-get -y update
#sudo apt-get -y install nginx

sudo ufw allow 'Nginx Full'

sudo echo "server {
        server_name $DOMAIN;

        location / {
                proxy_pass         'http://127.0.0.1:8888';     
   }
}
" >> /etc/nginx/sites-available/$DOMAIN

sudo ln -s /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/

# NGINX setup complete and point to localhost:8888 

# sudo apt-get -y upgrade

# install pip package manager
# sudo apt-get install -y python3-pip

# install packages for vit env setup
# sudo apt-get install build-essential libssl-dev libffi-dev python3-dev

# sudo apt-get install -y python3-venv

mkdir ~/environments
cd ~/environments

pyvenv jupyter-notebook

source jupyter-notebook/bin/activate


python3 -m pip install jupyter


# making Jupyter notebook publicly available

# cd ~/environments/jupyter-notebook

## Generate a Jupyter notebook configuration file
jupyter notebook -y --generate-config

## Add the following lines to your config file.
echo "c.NotebookApp.allow_origin = '*'
c.NotebookApp.ip = '0.0.0.0'" >> ~/.jupyter/jupyter_notebook_config.py


## Install Certbot
sudo add-apt-repository -y ppa:certbot/certbot
sudo apt-get update
sudo apt-get -y install python-certbot-nginx

sudo certbot --nginx -d  $DOMAIN


jupyter notebook --allow-root

# Restart Nginx
    sudo systemctl restart nginx
